### PR TITLE
Set environment variables by ENV instruction

### PR DESCRIPTION
**Pull request by igrep**
This change makes the environment variables defined in this Dockerfile
reusable in other Dockerfile-s deriving from this Dockerfile.

### CODE REVIEW

**Comment by dkfi** [comment]
Hi @igrep, thanks for the PR.
I'm not sure I grasped the idea behind your suggestion. Here is my test:

```
kristian@kristian:/tmp$ cat Dockerfile 
FROM dkfi/docker-oracle-xe-10g
RUN echo "this image inherits from dkfi/docker-oracle-xe-10g" >> /tmp/text.txt
kristian@kristian:/tmp$ docker build -t tester .
Sending build context to Docker daemon 53.32 MB
Step 1 : FROM dkfi/docker-oracle-xe-10g
 ---> 6385ed593bdc
Step 2 : RUN echo "this image inherits from dkfi/docker-oracle-xe-10g" >> /tmp/text.txt
 ---> Running in d125e90413cc
 ---> f1e3a715e977
Removing intermediate container d125e90413cc
Successfully built f1e3a715e977
kristian@kristian:/tmp$ docker run -it --rm tester bash
root@f5ee9cd0a809:/# echo $ORACLE_HOME
/usr/lib/oracle/xe/app/oracle/product/10.2.0/server
root@f5ee9cd0a809:/# cat /tmp/text.txt 
this image inherits from dkfi/docker-oracle-xe-10g
```

This shows that a new image built by deriving dkfi/docker-oracle-xe-10g is still able to see the environment variables without having to insert those values in /etc/bash.bashrc. Is this what you meant?

**Comment by igrep** [comment]
The environment variables written in bashrc are visible _only from bash_.
So, for example, `RUN echo $ORACLE_HOME` in the deriving Dockerfile wouldn't result in as expected.

**Comment by dkfi** [comment]
OK. I now understand what you meant. It definely makes sense to me. What about rewriting your series of RUN commands into a single statement to keep number of layers minimum?

**Comment by igrep** [comment]
> What about rewriting your series of RUN commands into a single statement to keep number of layers minimum?

:confused: What do you mean? This patch doesn't contain any RUN commands at least in the code after changing...

**Comment by dkfi** [comment]
Doh! :) Sorry about that. I read the diff the other way around. I was kinda in rush I guess ;)

**Pull request merged**
